### PR TITLE
hotfix-core-svc-feat(global-search): controlling index size for better search results experiences

### PR DESCRIPTION
**Pull request by rachadiannovansyah**
Changes:
- Now can controller index size by env, so can make the wide searches results

cc: https://github.com/orgs/jabardigitalservice/teams/jds-backend

Evidence
project: Portal Jabar
title: controlling index size for better search results experiences
participants: @rachadiannovansyah @ayocodingit

### CODE REVIEW

**Comment by ayocodingit** [comment]
> Changes:
> - Now can controller index size by env, so can make the wide searches results
> 
> cc: https://github.com/orgs/jabardigitalservice/teams/jds-backend
> 
> Evidence
> project: Portal Jabar
> title: controlling index size for better search results experiences
> participants: @rachadiannovansyah 

Can you explanation about index size in elastic?

**Comment by rachadiannovansyah** [comment]
> > Changes:
> > 
> > * Now can controller index size by env, so can make the wide searches results
> > 
> > cc: https://github.com/orgs/jabardigitalservice/teams/jds-backend
> > Evidence
> > project: Portal Jabar
> > title: controlling index size for better search results experiences
> > participants: @rachadiannovansyah
> 
> Can you explanation about index size in elastic?

The index size function is to retrieve how many documents references the search results get. Existing behavior is constrained by `params.PerPage`value. It's good but does not really have a wide of results. So now, Index Size is controlled by env. The `params.PerPage` is only used for paginate only.

**Review by ayocodingit — APPROVED** [review]

**Comment by ayocodingit** [comment]
> > > Changes:
> > > 
> > > * Now can controller index size by env, so can make the wide searches results
> > > 
> > > cc: https://github.com/orgs/jabardigitalservice/teams/jds-backend
> > > Evidence
> > > project: Portal Jabar
> > > title: controlling index size for better search results experiences
> > > participants: @rachadiannovansyah
> > 
> > 
> > Can you explanation about index size in elastic?
> 
> The index size function is to retrieve how many documents references the search results get. Existing behavior is constrained by `params.PerPage`value. It's good but does not really have a wide of results. So now, Index Size is controlled by env. The `params.PerPage` is only used for paginate only.

oh, I see, for now, we sorted by all results not by page result, right?

**Comment by rachadiannovansyah** [comment]
> > > > Changes:
> > > > 
> > > > * Now can controller index size by env, so can make the wide searches results
> > > > 
> > > > cc: https://github.com/orgs/jabardigitalservice/teams/jds-backend
> > > > Evidence
> > > > project: Portal Jabar
> > > > title: controlling index size for better search results experiences
> > > > participants: @rachadiannovansyah
> > > 
> > > 
> > > Can you explanation about index size in elastic?
> > 
> > 
> > The index size function is to retrieve how many documents references the search results get. Existing behavior is constrained by `params.PerPage`value. It's good but does not really have a wide of results. So now, Index Size is controlled by env. The `params.PerPage` is only used for paginate only.
> 
> oh, I see, for now, we sorted by all results not by page result, right?

right for this case we use [this package](https://pkg.go.dev/sort) as a sub-layer to present data from elastic search results. 
so sort by elastic is used by `_score` and second sort by `created_at` by unix time comparing.

**Comment by rachadiannovansyah** [comment]
I think it was enough for now, it will be merged soon. if any questions about it you can mention me yaa, thanks!

**Pull request merged**
