### PR TITLE
refactor migrations pre-dev

### PR DESCRIPTION
**Pull request by rachadiannovansyah**
Overview:
- No longer needs backtick on migration
- Unify migration to add column or table to one file `'initialize schema'` (bcs currently still pre-development)
- Has been discussed with our mates @khihadysucahyo 

@jabardigitalservice/jds-backend 

Evidence:
project: Portal Jabar
title: Refactor migrations development
participants: @novansyaah @khihadysucahyo @fimz17

### CODE REVIEW

**Comment by khihadysucahyo** [comment]
nice refactor dude, there are some minor notes, I think we need to remove the db engine setter(?): `ENGINE=InnoDB DEFAULT CHARSET=latin1;` which might be easier to migrate to another driver like postgres or others in the future

**Review by khihadysucahyo — APPROVED** [review]

**Comment by khihadysucahyo** [comment]
gas @firmanJS https://portal-jabar-staging.rover.digitalservice.id/careers

**Comment by rachadiannovansyah** [comment]
> nice refactor dude, there are some minor notes, I think we need to remove the db engine setter(?): `ENGINE=InnoDB DEFAULT CHARSET=latin1;` which might be easier to migrate to another driver like postgres or others in the future

ahh I was forgot with this, here we go https://github.com/jabardigitalservice/portal-jabar-services/pull/43/commits/2af8ead957b7df4bdc6a792e097da0d5c3acaf0c

**Review by firmanJS — APPROVED** [review]
LGTM !

**Comment by firmanJS** [comment]
> gas @firmanJS https://portal-jabar-staging.rover.digitalservice.id/careers

tolong sediain enndpoint ini :runner: 
https://portal-jabar-staging.rover.digitalservice.id/siap

**Pull request merged**
