### PR TITLE
core-svc-enhance(google-translate): initial setup google translate api 

### PR DESCRIPTION
**Pull request by rachadiannovansyah**
## Overview
- initial setup of Google Translate API 

## Changes
- add setup config for usage of Google Translate API
- all the keys secured on .env
- implement `translatedText` feature on the whole module event get by id API

## Docs
- https://cloud.google.com/translate/docs/reference/rest/v2/translate

## Links
- Click Up: https://app.clickup.com/t/860rwcabh

## To Do
- [x] update env. on the staging/production environments

## Evidence:
project: Portal Jabar
title: Initial setup penggunaan Google Translate API Portal Jabar
participants: @rachadiannovansyah @feriahmad @ayocodingit

### CODE REVIEW

**Review by ayocodingit — COMMENTED** [review]
Please explain the billing details for using the Google Translate service in the Pull Request description

**Comment by rachadiannovansyah** [comment]
> Please explain the billing details for using the Google Translate service in the Pull Request description

about the billing, as we have discussed with our DevOps team @feriahmad , we've already set the threshold for the initial usage of the requirement. Also, we're monitoring the usage on the [Grafana](https://grafana.digitalservice.id/d/a87d3233-7a7e-462e-bc64-801518f0f1e9/billing?orgId=1&viewPanel=6) for the awareness.

here if you want to get details for further information https://cloud.google.com/translate/pricing

**Review by ayocodingit — APPROVED** [review]

**Comment by azophy** [comment]
sorry for the late review. 

I'm curious as it seems that this implementation is based on synchronous request. Do you have any information about the response time of the translate service? Is there any risk that the request to Google would be a bottleneck @rachadiannovansyah  ?

**Comment by rachadiannovansyah** [comment]
> sorry for the late review.
> 
> I'm curious as it seems that this implementation is based on synchronous request. Do you have any information about the response time of the translate service? Is there any risk that the request to Google would be a bottleneck @rachadiannovansyah ?

hi @azophy , a good question to consider regarding the implementation. Sure, this request makes us spend longer on latency. By the way, this Pull Request is just for the initial setup for usage of Google Translate, but I slipped a rude experiment to try it on one of the features. 

Here I present the information of experiment:

No translation process:
image


With the translation process:
image

The synchronous translation cost us about it. Will improve on to the next. Thanks, @azophy .

**Pull request merged**
